### ISSUE TITLE
* PRNG seeding failed

### ISSUE THREAD

**Issue by simonmorley** [curl/curl#1268]
Running libcurl on LEDE master - libcurl version 7.52.1-2

We're seeing the following error:

```
* PRNG seeding failed
```

I've narrowed this down to this:

```
   curl_formadd(&post, &last, CURLFORM_COPYNAME, "data",
   CURLFORM_FILE, options.archive, CURLFORM_END);
```

If I remove the formadd - the request works. I don't see why it's failing here or why all other requests work.

**Comment by jay** [comment]
That's because random number generation is used to make a unique hash for the form boundary. What is the curl_version()? There were two fixes after 7.52.1 that may have fixed the issue, 807698d and afd1564. I suggest you build from the repo master and let us know if you can still reproduce.

**Comment by simonmorley** [comment]
OK cool, I'll recompile and update when I've progressed.

**Comment by simonmorley** [comment]
Missed your note about curl version:

```
curl - 7.52.1-2 - A client-side URL transfer utility
libcurl - 7.52.1-2 - A client-side URL transfer library
```

To get it merged into LEDE, I'll need a version number though...

https://github.com/lede-project/source/blob/master/package/network/utils/curl/Makefile#L11

**Comment by jay** [comment]
Just test with the repo master, and let us know. There is a release in a few days 7.53.0 so conceivably you could use that, assuming the issue was already fixed.

**Comment by bagder** [comment]
Also relevant to this issue is what TLS backend you used when you saw this problem?

**Comment by bagder** [comment]
@simonmorley can we close this?

**Comment by simonmorley** [comment]
Haven't built yet, will try later today with 7.53.0

**Comment by vosmani** [comment]
Any updates on this? Have tried with the version below and still the same problem (curl: (27) PRNG seeding failed)

```
curl 7.53.1 (mipsel-openwrt-linux-gnu) libcurl/7.52.1 mbedTLS/2.4.0
Protocols: file ftp ftps http https
Features: IPv6 Largefile SSL
```

**Comment by jay** [comment]
> libcurl/7.52.1 mbedTLS/2.4.0

As noted there were two fixes after 7.52.1 for this issue. You are using curl 7.53.1 but it is using an older version of the library which is uncommon, usually they are the same. Likely an older shared library is being loaded, run ldd to confirm

**Comment by simonmorley** [comment]
I believe the update fixed this for us.

**Comment by jay** [comment]
> I believe the update fixed this for us.

Great, thanks for letting us know.
