### ISSUE TITLE
Stream error in the HTTP/2 framing layer for empty POST requests

### ISSUE THREAD

**Issue by jeroen** [curl/curl#1587]
A bit of an edge case, hopefully someone can provide some some insight.

We get an HTTP2 error in R when the user tries to perform a form post, but with zero arguments (ie. empty body). The problem only and consistently appears when HTTP2 is enabled. 

```
> ocpu_post_multipart('/library/base/R/Sys.time')
* Hostname in DNS cache was stale, zapped
*   Trying 2400:cb00:2048:1::681b:9912...
* TCP_NODELAY set
* Connected to cloud.opencpu.org (2400:cb00:2048:1::681b:9912) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni70697.cloudflaressl.com
*  start date: Jun 17 00:00:00 2017 GMT
*  expire date: Dec 24 23:59:59 2017 GMT
*  subjectAltName: host "cloud.opencpu.org" matched cert's "*.opencpu.org"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x103749e00)
> POST /ocpu/library/base/R/Sys.time HTTP/2
Host: cloud.opencpu.org
User-Agent: R (3.4.0 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 0

* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
* Closing connection 1
 Show Traceback
 
 Rerun with Debug
 Error in curl_fetch_memory(url, handle = handle) : 
  Stream error in the HTTP/2 framing layer 
```

When HTTP2 is disabled using `CURLOPT_HTTP_VERSION` then the request succeeds.

```
*   Trying 2400:cb00:2048:1::681b:9812...
* TCP_NODELAY set
* Connected to cloud.opencpu.org (2400:cb00:2048:1::681b:9812) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni70697.cloudflaressl.com
*  start date: Jun 17 00:00:00 2017 GMT
*  expire date: Dec 24 23:59:59 2017 GMT
*  subjectAltName: host "cloud.opencpu.org" matched cert's "*.opencpu.org"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
> POST /ocpu/library/base/R/Sys.time HTTP/1.1
Host: cloud.opencpu.org
User-Agent: R (3.4.0 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 0

< HTTP/1.1 201 Created
< Date: Sun, 18 Jun 2017 20:55:51 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
```

Unfortunately I have not yet been able to reproduce this using the command line, only via `libcurl` bindings.

**Comment by jeroen** [comment]
I have put together a basic `c` example that reproduces the problem. I am using:

```
curl 7.54.1 (x86_64-apple-darwin16.6.0) libcurl/7.54.1 OpenSSL/1.0.2l zlib/1.2.8 nghttp2/1.23.1
```


To re-emphasize, the problem only appears under HTTP/2 if the user tries to perform a multipart post with 0 arguments. In the example below, we get `Stream error in the HTTP/2 framing layer ` but the problem is solved if we uncomment the `curl_formadd()` line.


```c
/* This example will fail over HTTP2 but not HTTP 1.1
 * The problem goes away if we uncomment the curl_formadd() line
 */

#include <stdio.h>
#include <curl/curl.h>

int main(void){  

  /* In windows, this will init the winsock stuff */
  curl_global_init(CURL_GLOBAL_ALL);

  /* get a curl handle */
  CURL * curl = curl_easy_init();
  curl_easy_setopt(curl, CURLOPT_URL, "https://cloud.opencpu.org/ocpu/library/base/R/list");
  curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2TLS);
  curl_easy_setopt(curl, CURLOPT_VERBOSE, 1);

  /* make the multipart */
  struct curl_httppost* post = NULL;
  struct curl_httppost* last = NULL;

  /* comment this out to post empty form */
  //curl_formadd(&post, &last, CURLFORM_COPYNAME, "test", CURLFORM_COPYCONTENTS, "123", CURLFORM_END);
  
  /* Perform the request, res will get the return code */
  curl_easy_setopt(curl, CURLOPT_HTTPPOST, post);
  CURLcode res = curl_easy_perform(curl);

  /* Check for errors */
  if(res != CURLE_OK)
      fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));

  /* always cleanup */
  curl_easy_cleanup(curl);
  curl_global_cleanup();
  return 0;
}
```

**Comment by bagder** [comment]
Can you still reproduce this? I'm trying current git master on both Linux and mac and I don't get this problem. I only get libcurl to hang basically, probably because of the blank POST data. But no error.

Does the URL used in this recipe still work? I figured it should also be possible to just send this to any server that returns a 200 for the post.

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!

**Comment by moko-als** [comment]
We've got a similar issue in our code. In our code curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, 0) is always called because otherwise no Content-length: header will be passed in empty POST request and this is not correct. And it has this strange side-effect only with HTTP2.

```
/* This example will fail over HTTP2 but not HTTP 1.1
 * The problem goes away if we comment the CURLOPT_POSTFIELDSIZE, 0 line
* or CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2 line
 */

#include <stdio.h>
#include <curl/curl.h>

int main(void){

  /* In windows, this will init the winsock stuff */
  curl_global_init(CURL_GLOBAL_ALL);

  /* get a curl handle */
  CURL * curl = curl_easy_init();
  curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, 0);
  curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "");
  
  curl_easy_setopt(curl, CURLOPT_URL, "https://example.com/");
  curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2);
  curl_easy_setopt(curl, CURLOPT_VERBOSE, 1);

  /* make the multipart */
  struct curl_httppost* post = NULL;
  struct curl_httppost* last = NULL;

  curl_formadd(&post, &last, CURLFORM_COPYNAME, "test", CURLFORM_COPYCONTENTS, "123", CURLFORM_END);
  curl_easy_setopt(curl, CURLOPT_HTTPPOST, post);

  /* Perform the request, res will get the return code */
  CURLcode res = curl_easy_perform(curl);

  /* Check for errors */
  if(res != CURLE_OK)
      fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));

  /* always cleanup */
  curl_easy_cleanup(curl);
  curl_global_cleanup();
  return 0;
}
```
