### ISSUE TITLE
libcurl crash in on_stream_close

### ISSUE THREAD

**Issue by HuiQiao502** [curl/curl#17869]
### I did this

**Background**
Our software uses libcurl to communicate with the backend. However, a crash occurred. Please refer to the function stack below, which was obtained from the core dump file.

Thread 1 (LWP 3087):
#0  0x0000007fa58eaae8 in on_stream_close (session=0x7f64038b60, stream_id=545, error_code=5, userp=0x7f64036f60) at http2.c:1331
#1  0x0000007fa597ba08 in nghttp2_session_close_stream (session=session@entry=0x7f64038b60, stream_id=545, error_code=5) at /home/jenkins/workspace/workspace/cns3.0_gp_sop3_linux_release_job/recipes-svw-cns3.0/dev/src/libs/ext-nghttp2/1/workspace/nghttp2-1.32.1/lib/nghttp2_session.c:1179
#2  0x0000007fa5980104 in nghttp2_session_mem_send_internal (session=session@entry=0x7f64038b60, data_ptr=data_ptr@entry=0x7fa2ddc200, fast_cb=fast_cb@entry=0) at /home/jenkins/workspace/workspace/cns3.0_gp_sop3_linux_release_job/recipes-svw-cns3.0/dev/src/libs/ext-nghttp2/1/workspace/nghttp2-1.32.1/lib/nghttp2_session.c:2946
#3  0x0000007fa5981174 in nghttp2_session_send (session=0x7f64038b60) at /home/jenkins/workspace/workspace/cns3.0_gp_sop3_linux_release_job/recipes-svw-cns3.0/dev/src/libs/ext-nghttp2/1/workspace/nghttp2-1.32.1/lib/nghttp2_session.c:3214
#4  0x0000007fa58e8c08 in http2_data_done (cf=0x7f64036f60, data=0x7ed015c080, premature=<optimized out>) at http2.c:292
#5  0x0000007fa58eb39c in cf_h2_cntrl (cf=0x7f64036f60, data=0x7ed015c080, event=<optimized out>, arg1=<optimized out>, arg2=<optimized out>) at http2.c:2496
#6  0x0000007fa58c08e8 in Curl_conn_cf_cntrl (cf=0x7f64036f60, data=data@entry=0x7ed015c080, ignore_result=ignore_result@entry=true, event=event@entry=7, arg1=arg1@entry=1, arg2=arg2@entry=0x0) at cfilters.c:501
#7  0x0000007fa58c0db8 in cf_cntrl_all (arg2=0x0, arg1=1, event=7, ignore_result=true, data=0x7ed015c080, conn=0x7f6404ae00) at cfilters.c:598
#8  Curl_conn_ev_data_done (data=data@entry=0x7ed015c080, premature=premature@entry=true) at cfilters.c:598
#9  0x0000007fa58fc8dc in multi_done (data=data@entry=0x7ed015c080, status=CURLE_SEND_ERROR, premature=premature@entry=true) at multi.c:694
#10 0x0000007fa58fec48 in multi_runsingle (multi=multi@entry=0x2ddcc500, nowp=nowp@entry=0x7fa2ddc5f0, data=data@entry=0x7ed015c080) at multi.c:2462
#11 0x0000007fa58ff88c in curl_multi_perform (multi=0x2ddcc500, running_handles=running_handles@entry=0x7fa2ddc808) at multi.c:2702

**Version:**
curl 8.5.0 (aarch64-oe-linux-gnu) libcurl/8.5.0 OpenSSL/1.1.1q zlib/1.2.11 c-ares/1.19.1 nghttp2/1.32.1

**reproduce infromation**
This issue only happened twice.it look like when timeout happened, this issue could reproduce.
curlMultiInfoRead(0) -> msg.data.result=28 text=Timeout was reached

### I expected the following

Could you please help to check whether it is a known issue?
Because it is really sporadic, we can not provide more information at present.

thanks a lot.

### curl/libcurl version

curl 8.5.0

### operating system

Linux

**Comment by icing** [comment]
I believe this was fixed via  #12562 in 3538027. Can you reproduce the problem with a recent curl version/master?

**Comment by HuiQiao502** [comment]
> I believe this was fixed via [#12562](https://github.com/curl/curl/pull/12562) in [3538027](https://github.com/curl/curl/commit/35380273b9311cf0741e386284310fa7ca4d005e). Can you reproduce the problem with a recent curl version/master?

Thanks for the quick answer. It only happened twice in production and can not reproduce in our test rack.

**Comment by icing** [comment]
If you need commercial support for 8.5.0, [there are options](https://curl.se/support.html). I'll close this issue as fixed. Feel free to report back if you can reproduce on the latest version/master. Thanks!

**Comment by dfandrich** [comment]
I suggest trying the latest versions of both libcurl and nghttp2. The versions
you are using are quite old and there have been many bugs fixed since then. If
the latest still show issues then you'll find more interest here in solving
them.
*EDIT:* I completely missed this fast-moving thread until a moment too late!

**Comment by HuiQiao502** [comment]
> If you need commercial support for 8.5.0, [there are options](https://curl.se/support.html). I'll close this issue as fixed. Feel free to report back if you can reproduce on the latest version/master. Thanks!

thanks a lot, we will try this patch.
