### ISSUE TITLE
curl does not build on AIX due to issues with openssl and zlib include files - free_func redefined

### ISSUE THREAD

**Issue by aixtools** [curl/curl#2075]
### I did this
git clone https://github.com/curl/curl.git curl-7.57.0.0
cd curl-7.57.0.0
./buildconf
./configure ...
make

### I expected the following
that make would complete, however it ends with:

### build results - one example
michael@x071:[/data/prj/aixtools/curl/curl-7.57.0/lib]grep -n free_func http_ntlm.lst
8303:"/usr/include/openssl/crypto.h", line 428.44: 1506-492 (I) Redefinition of free_func hides previous definition.
8307:"/usr/include/openssl/crypto.h", line 518.44: 1506-275 (S) Unexpected text free_func encountered.
8308:"/usr/include/openssl/crypto.h", line 523.47: 1506-275 (S) Unexpected text free_func encountered.
8762:"/usr/include/openssl/bio.h", line 655.66: 1506-492 (I) Redefinition of free_func hides previous definition.
10343:"/usr/include/openssl/asn1.h", line 925.46: 1506-275 (S) Unexpected text free_func encountered.
10353:"/usr/include/openssl/asn1.h", line 1079.49: 1506-275 (S) Unexpected text free_func encountered.
10365:"/usr/include/openssl/objects.h", line 1009.31: 1506-275 (S) Unexpected text free_func encountered.
10848:"/usr/include/openssl/ec.h", line 858.41: 1506-275 (S) Unexpected text free_func encountered.
10849:"/usr/include/openssl/ec.h", line 870.44: 1506-275 (S) Unexpected text free_func encountered.
11134:"/usr/include/openssl/ecdsa.h", line 243.43: 1506-492 (I) Redefinition of free_func hides previous definition.
11404:"/usr/include/openssl/ecdh.h", line 118.42: 1506-492 (I) Redefinition of free_func hides previous definition.
11471:"/usr/include/openssl/rsa.h", line 505.66: 1506-492 (I) Redefinition of free_func hides previous definition.
12218:"/usr/include/openssl/dh.h", line 222.65: 1506-492 (I) Redefinition of free_func hides previous definition.
12247:"/usr/include/openssl/dsa.h", line 232.66: 1506-492 (I) Redefinition of free_func hides previous definition.
13387:"/usr/include/openssl/x509_vfy.h", line 551.52: 1506-492 (I) Redefinition of free_func hides previous definition.
13808:"/usr/include/openssl/x509.h", line 845.67: 1506-492 (I) Redefinition of free_func hides previous definition.
15495:"/usr/include/openssl/ssl.h", line 2478.66: 1506-492 (I) Redefinition of free_func hides previous definition.
15496:"/usr/include/openssl/ssl.h", line 2485.49: 1506-492 (I) Redefinition of free_func hides previous definition.
15497:"/usr/include/openssl/ssl.h", line 2491.45: 1506-492 (I) Redefinition of free_func hides previous definition.
### curl/libcurl version

[curl -V output]

### operating system
AIX 5.3 TL7 and AIX 6.1 TL9, xlc-v11, patch 20

**Comment by bagder** [comment]
Please try #2074 and see if that fixes the problem for you!

**Comment by aixtools** [comment]
After several mails - to get hints - I got to the point I was comparing curl_ntlm_core.c (that builds) and http_ntlm.c

Both include the file urldata.h - BUT - the key difference is that curl_ntlm_core.c does all it ssl.h related checks before including urldata.h while http_ntlm.c, curl_ntlm_wb.c, vauth/ntlm.c, and vtls/openssl.c were doing that AFTER urldata.h

The patch attached fixes the issue. The final order - I expect to be determined by others wiser than myself!

[aix-free-func.txt](https://github.com/curl/curl/files/1466923/aix-free-func.txt)

**Comment by bagder** [comment]
@aixtools: the approach in #2074 seems less error-prone and preferred anyway since it reduces the amount of unnecessary includes we do for files in general.

**Comment by aixtools** [comment]
I do not think the solution proposed for #2074 would resolve this - as I do not see it fixing the files I see failing. However, after my patch above (and some manual editing of src/Makefile and lib/Makefile - different issue) - the build succeeds.

**Comment by bagder** [comment]
That is now pushed to master so you can just update and see...

**Comment by aixtools** [comment]
I cloned the master again, editted the Makefiles - but they end with:

Making all in cmdline-opts
Target "all" is up to date.
Target "all" is up to date.
make: 1254-002 Cannot find a rule to create target tool_hugehelp.c from dependencies.
Stop.
make: 1254-004 The error code from the last command is 1.


Stop.
make: 1254-004 The error code from the last command is 1.


Stop.

So - on the one hand, seems the lib directory is building - but something else is broken now.

root@x064:[/data/prj/aixtools/curl/src/curl-7.57.0.1/lib]make
        make  all-am
Target "all-am" is up to date.

As such - seems this issue may be closed!

**Comment by bagder** [comment]
That part didn't change between your updates though.

**Comment by bagder** [comment]
thanks for confirming the zlib/openssl issue is fixed!

**Comment by aixtools** [comment]
FYI: no idea. Just getting:

root@x064:[/data/prj/aixtools/curl/src/curl-7.57.0.1]make V=1
Making all in lib
        make  all-am
Target "all-am" is up to date.
Making all in src
Making all in ../docs
Making all in .
Target "all-am" is up to date.
Making all in cmdline-opts
Target "all" is up to date.
Target "all" is up to date.
make: 1254-002 Cannot find a rule to create target tool_hugehelp.c from dependencies.
Stop.
make: 1254-004 The error code from the last command is 1.


Stop.
make: 1254-004 The error code from the last command is 1.


Stop.

While the (earlier) clone:
oot@x064:[/data/prj/aixtools/curl/curl-7.57.0.0]make V=1
Making all in lib
        make  all-am
Target "all-am" is up to date.
Making all in src
Making all in ../docs
Making all in .
Target "all-am" is up to date.
Making all in cmdline-opts
Target "all" is up to date.
Target "all" is up to date.
Target "all-am" is up to date.
Target "all" is up to date.
Target "all-am" is up to date.
Target "all" is up to date.

**Comment by bagder** [comment]
Also, the logic that generates `tool_hugehelp.c` has not changed at all since 7.55.1. It seems your build successes vary based on things outside of the curl source tree...

**Comment by aixtools** [comment]
No idea why that happened. Might be spurious. Used the same process 
earlier - and all was well. - Although, I did try a short-cut, now that 
I think about it (called ./configure with no arguments ).

Will trash -and clone again...

**Comment by aixtools** [comment]
On 11/13/2017 2:55 PM, Daniel Stenberg wrote:
>
> Also, the logic that generates |tool_hugehelp.c| has not changed at 
> all since 7.55.1. It seems your build successes vary based on things 
> outside of the curl source tree...
>
That may be true - though I would not know what. Tried again - and it 
still fails. "Me is lost".

However, glad the zlib and openssl "argument" is resolved!
