### ISSUE TITLE
libcurl crash in curl_multi_remove_handle 

### ISSUE THREAD

**Issue by johannes1971** [curl/curl#3710]
I'm downloading data through an HTTP connection using the multi interface. I get frequent crashes when calling curl_multi_remove_handle on the handle. For example:

- client wishes to abort transfer, calls curl_multi_remove_handle to remove the handle from the multicurl object -> crash.
- remote side closes connection, curl_multi_remove_handle called from the callback (upon receiving CURL_POLL_REMOVE) -> crash.

There is either a single, or two connections open. I get the impression that this happens when there is incoming data that has not yet been processed by the application at the time when url_multi_remove_handle is called, but this could be mistaken.

I'm using version libcurl/7.61.1-DEV WinSSL zlib/1.2.11, taken from vcpkg, and running on Windows 7. According to the debugger the crash happens here:

    /* make sure there's no pending message in the queue sent from this easy
       handle */
    for(e = multi->msglist.head; e; e = e->next) {
        struct Curl_message *msg = e->ptr; 

    // e->ptr == nullptr, so it crashes when dereferenced in the if-statement below

    if(msg->extmsg.easy_handle == easy) {
        Curl_llist_remove(&multi->msglist, e, NULL);
        /* there can only be one from this specific handle */
        break;
        }
    }

For the rest, the callstack only contains my own code. Thanks in advance!

**Comment by bagder** [comment]
1. It would really help if you can provide us with a sample program that reproduces the problem. This description alone makes it really hard for us to act on it or even look for something that could explain this.
2. It is odd (or perhaps downright wrong) that vcpkg ships a `-DEV` curl version since that's not a released version.
3. 7.61.1 is a couple of releases old and this description resembles some problems we have fixed recently in curl so it might be worth trying out the latest curl version to see if the problem is already fixed there.

**Comment by johannes1971** [comment]
Ok, it appears I put a little too much faith in vcpkg. I rolled back to the previous version we were using (7.45) and everything worked just fine. I haven't been able to go forwards to 7.64.1 yet; there is a binary download in the downloads section but it requires various crypto libraries that aren't included, and I don't feel up to trying to build those myself (I'm still getting therapy from the last time I tried building OpenSSL). 

I have raised a bug on vcpk regarding the -dev version.

**Comment by jay** [comment]
> there is a binary download in the downloads section but it requires various crypto libraries that aren't included

which one

**Comment by johannes1971** [comment]
> which one

This one: https://curl.haxx.se/windows/ It requires libcrypto-1_1-x64.dll and libssl-1_1-x64.dll.

**Comment by jay** [comment]
Ok I see it. The dependend dlls can be found at [here](https://ci.appveyor.com/project/curlorg/curl-for-win/builds/23390319/artifacts) for 7.64.1. You're looking for openssl-1.1.1b-win32-mingw.zip or openssl-1.1.1b-win64-mingw.zip

@vszakats is it possible to include those DLLs in the curl release since they are required by libcurl dll?

**Comment by vszakats** [comment]
No hard data here, but I assume that the `.dll` from the `curl` package is used by much less people than `curl.exe` itself (which doesn't require any extra `.dll`s), so for most people the bundled `.dll` dependencies would be extra bloat, which bloat would only be getting larger and larger as more dependencies get added in the future (and the existing ones grow). The current layout is also fairly modular, extendable and maintainable. These are the main reasons for the current packaging method.

One thing that could be implemented, is an _additional_ "all-in-one" distribution package, that bundles the complete dependency tree (headers, `.exe`s, `.dll`s, static libraries, licences and other docs) into a single downloadable archive. This would require a script that takes all existing singular archives, unpack, merge and repack them. But first, a sensible, common directory layout would need to be thought out. Versioning of this archive would also pose a new problem, so that the name/version of the package reflect the versions of all included dependencies. Overall, this would create a Git-for-Windows/MSYS2-like distro, but centered around curl. It would be quite nice, but it feels like duplicate effort compared to these projects and also in terms of testing/maintenance. Also, such larger scope was not my goal with curl-for-win.

Anyhow, if someone is interested in creating a shell script (preferably POSIX-compliant) that does something like the above, I may be able tackle it to the current build script and upload the resulting "unified" archive for distribution. Or, all this can be done fully as a 3rd party script.

Everything considered I'm more in favour of offering these packages separately.

**Comment by jay** [comment]
> Everything considered I'm more in favour of offering these packages separately.

I agree.
