### ISSUE TITLE
Can't cross-compile for iOS on macOS 10.15

### ISSUE THREAD

**Issue by ecnepsnai** [curl/curl#4367]
This issue is basically the same as #3189 which was timed out and locked.

Summary of that issue: I am unable to build libcurl for iOS platforms on macOS 10.14 because:

> We can't compile without socket() support!

I have the Xcode Command Line Tools installed, and xcode-select is pointing at the correct binary of Xcode. I am using the GM Seed of Xcode 11.

```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
$ xcode-select -v
xcode-select version 2354.
```

In the previous issue I noted a possible workaround that you could install a package that puts headers back in /usr/include,
however I've found that I can no longer locate that package, and it doesn't appear to be supported by Apple any more.

Here's the full build log: [build.log](https://github.com/curl/curl/files/3617915/build.log), but some interesting parts I found were:

```
checking for proto/bsdsocket.h... no
checking for sys/socket.h... yes
checking for socket.h... no
checking if socket can be linked... yes
checking if socket is prototyped... no
checking if socket might be used... no
checking how to set a socket into non-blocking mode... unknown
configure: WARNING: cannot determine non-blocking socket method.
checking whether to enable Unix domain sockets... auto
Unix sockets:     enabled
Features:         SSL UnixSockets libz AsynchDNS NTLM NTLM_WB
url.c:57:2: error: "We can't compile without socket() support!"
#error "We can't compile without socket() support!"
```

I have not run into this issue on any other project that I compile on my mac, so I'm hesitant to believe that this issue doesn't involve curl.

**Comment by nickzman** [comment]
I still suspect that, if you're getting that error, your command line tools (which are installed separately from Xcode) are most likely out of date. Here's what I just tried:
```
export CFLAGS="-arch arm64 -pipe -Os -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=11.0"
./configure --disable-shared --enable-static --host="aarch64-apple-darwin" --with-darwinssl
make -j `sysctl -n hw.logicalcpu_max`
```
And libcurl built with no problems.

**Comment by ecnepsnai** [comment]
@nickzman I downloaded and installed the command line tools associated with the Xcode 11 GM Seed from developer.apple.com 
![Capture](https://user-images.githubusercontent.com/1607109/64991878-91cfa580-d887-11e9-9602-7a106b932605.PNG)

**Comment by bagder** [comment]
> checking if socket is prototyped... no

This means configure failed to find a socket prototype in any of the typical header files it checks. If we check earlier in the configure script when it checks for such header files, we see:

> checking for proto/bsdsocket.h... no
> checking for sys/socket.h... yes
> checking for socket.h... no

So it at least finds `sys/socket.h` to be present, but apparently it finds no "socket" in there?

**Comment by L1MeN9Yu** [comment]
@ecnepsnai 
When building on Mac OS Mojave an additional step is required:
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
`

**Comment by ecnepsnai** [comment]
@L1MeN9Yu If you look at the issue I referenced you'll see a comment by me using that file as a work around.

That package isn't provided by the command line tools any longer and therefor that workaround doesn't work.

**Comment by L1MeN9Yu** [comment]
@ecnepsnai 

[Xocde10 Release Notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes)

Command Line Tools
New Features
The Command Line Tools package installs the macOS system headers inside the macOS SDK. Software that compiles with the installed tools will search for headers within the macOS SDK provided by either Xcode at:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk

or the Command Line Tools at:

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

depending on which is selected using xcode-select.

The command line tools will search the SDK for system headers by default. However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so. As a workaround, an extra package is provided which will install the headers to the base system. In a future release, this package will no longer be provided. You can find this package at:

/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

 To make sure that you're using the intended version of the command line tools, run xcode-select -s <path to Xcode> or xcode select -s /Library/Developer/CommandLineTools after installing.

---
You can get sdk path by this command : `xcrun --sdk macosx/iphoneos/iphonesimulator --show-sdk-path` .Then add `-I$SDK_PATH/usr/include` to `CFLAGS` if you wan't install `macOS_SDK_headers_for_macOS_10.14.pkg
` 😂

**Comment by ecnepsnai** [comment]
@L1MeN9Yu I'm using **Xcode 11**, not 10 and that installer is not included in **Xcode 11**.

Your suggestion to include the header path in the CFLAGS results in the same error where sys/socket.h is found but socket can not be prototyped.

**Comment by olbrichj** [comment]
So this error is resulting from the missing header files mentioned by @L1MeN9Yu. I opened a similar issue almost a year ago. BUT the problem arises again, as that was the last time they provided the header installer.
Currently the script looks into /usr/include. The suggestion -I$SDK_PATH/usr/include should fix it.
It would be great though if someone could update the documentation how to cross compile for iOS in the future.

**Comment by bagder** [comment]
> It would be great though if someone could update the documentation how to cross compile for iOS in the future.

Sounds like a great idea.

**Comment by ecnepsnai** [comment]
@olbrichj I'm still not able to get using -I to work though :(

```bash
ARCH=armv7
HOST=armv7
SDKDIR=$(xcrun --sdk iphoneos --show-sdk-path)

export CFLAGS="-arch ${ARCH} -pipe -Os -gdwarf-2 -isysroot ${SDKDIR} -I${SDKDIR}/usr/include -miphoneos-version-min=${IPHONEOS_DEPLOYMENT_TARGET} -fembed-bitcode"
export LDFLAGS="-arch ${ARCH} -isysroot ${SDKDIR}"
./configure --host="${HOST}-apple-darwin" \
   --disable-shared \
   --enable-static \
   --disable-smtp \
   --disable-pop3 \
   --disable-imap \
   --disable-ftp \
   --disable-tftp \
   --disable-telnet \
   --disable-rtsp \
   --disable-ldap \
   --with-darwinssl
make -j 4
```

It fails with the exact same error as if I don't include the -I option

**Comment by L1MeN9Yu** [comment]
@ecnepsnai 

I build succeed and get the static lib in lib/.libs.

Xcode version: Version 11.1 (11A1027)
macOS version: Catalina

```
ARCH=armv7
HOST=armv7
SDKDIR=$(xcrun --sdk iphoneos --show-sdk-path)
IPHONEOS_DEPLOYMENT_TARGET=9

echo ${SDKDIR}

export CFLAGS="-arch ${ARCH} -pipe -Os -gdwarf-2 -isysroot ${SDKDIR} -I${SDKDIR}/usr/include -miphoneos-version-min=${IPHONEOS_DEPLOYMENT_TARGET} -fembed-bitcode"
export LDFLAGS="-arch ${ARCH} -isysroot ${SDKDIR}"
./configure --host="${HOST}-apple-darwin" \
   --disable-shared \
   --enable-static \
   --disable-smtp \
   --disable-pop3 \
   --disable-imap \
   --disable-ftp \
   --disable-tftp \
   --disable-telnet \
   --disable-rtsp \
   --disable-ldap \
   --with-darwinssl
make -j 8
```

```
tree .libs                                                                                                                                                ✔  64  18:47:17
.libs
├── libcurl.a
├── libcurl.la -> ../libcurl.la
└── libcurl.lai
```

Maybe use the stable xcode to have a try?

**Comment by ecnepsnai** [comment]
I'm travelling right now, when I get back I'm going to format my Mac and do
a fresh install of the latest Xcode from the App Store on Catalina and will
post results.

**Comment by ecnepsnai** [comment]
On a clean-slate install of Catalina (Format + Install) I only installed Xcode 11.1 (11A1027) from the app store. I have made no other changes to the system or installed any other packages.

Trying to compile using the same commands given above return the same results, with the socket error.

```
IPHONEOS_DEPLOYMENT_TARGET=9.3
CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
ARCH=armv7
HOST=armv7
SDKDIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk
CFLAGS='-arch armv7 -pipe -Os -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/usr/include -miphoneos-version-min=9.3 -fembed-bitcode'
LDFLAGS='-arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk'
./configure --host=armv7-apple-darwin --disable-shared --enable-static --disable-smtp --disable-pop3 --disable-imap --disable-ftp --disable-tftp --disable-telnet --disable-rtsp --disable-ldap --with-darwinssl
make -j 4
```

```
url.c:57:2: error: "We can't compile without socket() support!"
#error "We can't compile without socket() support!"
 ^
1 error generated.
make[2]: *** [libcurl_la-url.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

I will try and leave my macbook in this state for as long as I can to help troubleshoot.

**Comment by L1MeN9Yu** [comment]
It seems that `Command Line Tools` isn't installed.
Could you build libcurl for host `x86_64`?

**Comment by ecnepsnai** [comment]
Xcode shows that the command line tools are installed. Building for x86_64 produces the same error.
<img width="912" alt="Screen Shot 2019-10-14 at 6 32 17 PM" src="https://user-images.githubusercontent.com/1607109/66793276-82a53d00-eeb1-11e9-83ee-38fcb3577bd8.png">

**Comment by L1MeN9Yu** [comment]
The system wide CLT is not installed.
try to  run `xcode-select --install` or just install `Homebrew`,The CLT will be asked to install automaticly.
Reference : https://github.com/Homebrew/brew/issues/5002#issuecomment-425707878

**Comment by ecnepsnai** [comment]
I installed the system-wide CLT using Xcode-select and retried compiling, it fails with the same socket() error.

```
% sudo xcode-select --install
Password: [...]
xcode-select: note: install requested for command line developer tools
% sudo xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by ecnepsnai** [comment]
@bagder Can remove that "needs-info-or-update" tag?

I think it's pretty clear that on a fresh install of Catalina (which we will see more of very soon as people buy new Macs) you can't compile curl.

**Comment by bagder** [comment]
What is clear is that you have a problem to build curl, yes. I don't think it has been shown that this is a universal problem or one that hasn't an available solution or fix. I'll try to get to testing this myself soon.

**Comment by bagder** [comment]
Works just fine for me. macOS upgraded to the latest Catalina.
~~~
$ ./src/curl -V
curl 7.67.0-DEV (x86_64-apple-darwin19.0.0) libcurl/7.67.0-DEV SecureTransport zlib/1.2.11 nghttp2/1.38.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS Debug HTTP2 IPv6 Largefile libz NTLM NTLM_WB SSL TrackMemory UnixSockets
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.15
BuildVersion:   19A602
$ uname -a
Darwin Daniels-mini2 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

**Comment by olbrichj** [comment]
@bagder I guess in this case it's about the iOS cross compile. The build directly for macOS did always work :)
If your cross-compile works, could you please also check whether /usr/include exists or not? On my machine it compiles (but it was a Catalina Beta and I can't test it right now).

**Comment by ecnepsnai** [comment]
I think the issue also has to do if you have a fresh install of Catalina VS upgrade from Mojave (and have installed Xcode/CLT in the past). I never had problems up until I had to get my Mac services and Apple replaced the SSD on it, forcing me to do a fresh install.

**Comment by olbrichj** [comment]
Upgrading to Mojave (last year) already resulted in the error. But on a clean install you will definitely face this problem.

**Comment by bagder** [comment]
Given all details given here, this seems like a tool and toolchain problem rather than a curl problem. There's nothing in curl that prevents this from working and in fact it works for many people if they just manage to get the toolchain correctly.

To me, it seems you should contact your toolchain vendor and have them fix this.

**Comment by olbrichj** [comment]
Apple won't do anything ;)

They explicitly moved it into their corresponding environments. On Mojave they provided a transition package, which will not exist on newer macs anymore (Catalina upwards). So in this case I guess curl will have to do something. Either update the documentation, so everyone knows how to build it correctly, or change something within the configure script.

**Comment by bagder** [comment]
> Either update the documentation

To say what?

> or change something within the configure script.

Suggestions and pull requests are welcome!

**Comment by Jayatubi** [comment]
After set the include path by `export CPPFLAGS="-I${SDK_ROOT}/usr/include"` I get another errror:
```
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/Users/jay/curl-unity/build/curl/curl-7.64.0':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
``` 
It fails duration the configuration phase.

**Comment by Jayatubi** [comment]
Finally I built the iOS lib successfully with `cmake`:
```
cmake $CURL_ROOT \
            -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN \
            -DDEPLOYMENT_TARGET=12.0 \
            -DENABLE_BITCODE=1 \
            -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT \
            -DOPENSSL_INCLUDE_DIR=$OPENSSL_ROOT/include \
            -DOPENSSL_CRYPTO_LIBRARY=$OPENSSL_ROOT/lib/libcrypto.a \
            -DOPENSSL_SSL_LIBRARY=$OPENSSL_ROOT/lib/libssl.a \
            -DNGHTTP2_INCLUDE_DIR=$NGHTTP2_ROOT/include \
            -DNGHTTP2_LIBRARY=$NGHTTP2_ROOT/lib/libnghttp2.a \
            -DUSE_NGHTTP2=ON \
            -DHTTP_ONLY=ON \
            -DCMAKE_USE_LIBSSH2=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_CURL_EXE=OFF

cmake --build $BUILD_DIR --config Release --target install -j8
```
And the cmake toolchain for iOS I used is from https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake

**Comment by ecnepsnai** [comment]
I found the issue - it was the CC used. I had it set to `CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang`. Unsetting that variable from my build script resolved the issue. My apologies for the confusion!

**Comment by manuyavuz-pointr** [comment]
FYI, this problem happens for people using https://github.com/gcesarmza/curl-android-ios repo to build curl for iOS (including me).

Repo has the following line in their `build_iOS.sh` script:
https://github.com/gcesarmza/curl-android-ios/blob/da6f0d2302ce7a9ea560871fe9e6e86398d5b584/curl-compile-scripts/build_iOS.sh#L36

```
export CC="$XCODE/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
```

This breaks the build, and removing that line from the script solves the issue.

I would open a PR on that repo but it seems not properly maintained for a long time. Therefore I think it's good to have this referred under this issue as well.

Thanks!
