### ISSUE TITLE
[libcurl] Multi interface does not indicate that new HTTP/2 stream cannot be added and existing streamed should be closed after a GOAWAY frame is received.

### ISSUE THREAD

**Issue by gadam0** [curl/curl#4839]
### I did this
I have an application that uses libcurl to communicate with an HTTP/2 server using the multi interface.
The application uses a long lived HTTP2 GET request with multipart data to push messages down to the client.
When the HTTP2 server sends a GOAWAY frame the curl multi handle continues to accept new requests that will fail.
There does not appear to be a way to determine that a GOAWAY frame has been sent so that a client can clean up long lived connections.

### I expected the following
I expected that either the libcurl API would provide some way to determine that a GOAWAY frame has been sent so that the client can clean-up or
that the multi-handle would clean-up and close the streams during a call to curl_multi_perform and then re-open a new connection when a new request is created.

### curl/libcurl version
curl 7.54.0 (x86_64-pc-linux-gnu) libcurl/7.54.0 OpenSSL/1.0.2g zlib/1.2.8 nghttp2/1.19.0

### operating system
Ubuntu 16.04

I have written a small C application uses libcurl that demonstrates this behavior and a simple HTTP/2 server using Python, twisted, and the 'h2' Python library.
https://gist.github.com/gadam0/c397a9950860c60edd86afb2e41897e5

**Comment by bagder** [comment]
You're using an outdated libcurl version. As recently as c1b6a384f9 (shipped in 7.66.0) we fixed a GOAWAY issue so I would rather recommend you upgrade to the latest version where I believe this issue doesn't exist.

**Comment by gadam0** [comment]
I rebuilt against the latest curl and nghttp2 libraries. Here is the new `--version` output.

```
curl 7.68.0-DEV (x86_64-pc-linux-gnu) libcurl/7.68.0-DEV OpenSSL/1.0.2g zlib/1.2.8 nghttp2/1.40.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

With the new version of curl the multi handle will create a new connection for the new request.
However the request to the `/downchannel` endpoint still appears to be open on the previous connection.
Is that right?

Is there anyway to determine that the old connection has died and a new connection has been created?
How should I clean up existing streams on the old connection?

This is the output when I run my program with the latest libcurl.
```
+ message CURLMcode 0
* Found bundle for host 127.0.0.1: 0xe2da50 [can multiplex]
* Multiplexed connection found!
* Re-using existing connection! (#0) with host 127.0.0.1
* Using Stream ID: 7 (easy handle 0xe52610)
> POST /message HTTP/2
Host: 127.0.0.1:8442
accept: */*
content-type: application/x-www-form-urlencoded

* Connection died, retrying a fresh connect
* Issue another request to this URL: 'http://127.0.0.1:8442/message'
* Found bundle for host 127.0.0.1: 0xe2da50 [can multiplex]
* Hostname 127.0.0.1 was found in DNS cache
*   Trying 127.0.0.1:8442...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8442 (#1)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0xe52610)
> POST /message HTTP/2
Host: 127.0.0.1:8442
accept: */*
content-type: application/x-www-form-urlencoded

* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200
< x-stream-id: 1
< content-type: multipart/related; boundary=b393cd07-43f7-4bd0-aa62-1f9dd3b390c6; type=application/json
<
DO_200_REPLY
+ Ending message loop.
* stopped the pause stream!
* stopped the pause stream!
* Closing connection 0
* stopped the pause stream!
* Connection #1 to host 127.0.0.1 left intact
```

**Comment by bagder** [comment]
> With the new version of curl the multi handle will create a new connection for the new request.

If you have PIPEWAIT set, that might be due to the bug (#4779) we've since fixed in #4784. If you don't have pipewait set, libcurl will prioritize speed before fewer connections.

> However the request to the /downchannel endpoint still appears to be open on the previous connection.

libcurl has a connection cache where it will leave connections open for a while after use, for subsequent transfers to (potentially) reuse. That's expected. They're closed when you close the handle.

**Comment by bagder** [comment]
Is this issue resolved now or do you still have an issue?

**Comment by gadam0** [comment]
My application is not using PIPEWAIT.

My concern is that the service that I am connecting to requires that a request on the downchannel endpoint is the first stream on a connection.
When curl creates a new connection for new requests internally then response messages on the downchannel may be lost because they are not associated with the same connection.

Another implementation that I have uses Netty to register an observer for events from the framing layer.
I use the callback for the GOAWAY frame to pause reading requests from a queue while a new connection is created and a new downchannel is established before processing requests from that queue.

I do not see any way to register for callbacks from the framing layer using the libcurl API.

I see that curl internally registers for frame callbacks from nghttp2.
https://github.com/curl/curl/blob/db9af34634e36d34067fff506915dcf7a783a1e2/lib/http2.c#L622
I also see that curl internally marks when a connection should be closed after a GOAWAY.
https://github.com/curl/curl/blob/master/lib/http2.c#L1385-L1389

But I do not see any way to determine that a GOAWAY has been received after running `curl_multi_perform` using the libcurl API.

Do you have any suggestion on how I can ensure that the first stream that is created on a connection is always a request on my downchannel endpoint?

**Comment by bagder** [comment]
> how can I ensure that the first stream that is created on a connection is always a request on my downchannel endpoint?

I've read this question several times but I still can't understand it. curl makes connections and streams and sends requests over them. I don't know what your "downchannel endpoint" is, or how curl interacts with it so I cannot comment on anything regarding that.

If you want a particular request to go over the first stream on a connection with libcurl, then I suggest you insist on a fresh connection for your transfer.

**Comment by bagder** [comment]
I don't see any bug mentioned here though, just questions on how the API should or could be used. If I'm mistaken, please let me know and highlight the problem. If not, I'll close this. We defer questions and discussions to the curl-library mailing list.

**Comment by gadam0** [comment]
I am using the term "downchannel endpoint" to mean a long lived GET request to an HTTP/2 server.
This is the behavior that is expected between the server and client:

A client establishes an HTTP/2 connection with the server and starts the long lived GET request.
That GET request allows the server to push messages down to the client.
The client reacts to those messages.

A client can also send a request to the server which may result in a another separate response on that long lived GET request (the downchannel).

But a new request from the client on a new connection without the long lived GET request may result in messages sent from the server to be lost.

This may not be a bug.
I do not see any way to access the information that I need within libcurl to know when I should remove and cleanup the handle for the long lived GET request and clean-up the multi-handle before I establish a new connection with a new multi-handle to create a new long lived GET request.
I am looking for information at the framing layer and that may require a code change and that would be a feature request.
Do you think I can address this issue without a change to libcurl?

**Comment by bagder** [comment]
Let me see if I understand this:

1. You do a request (A) that basically has a never-ending, chunked, response.
2. You then do other requests (B, C, ...) in parallel (perhaps on a separate connection) that might cause new chunked response parts to request A
3. At some point the connection for response A gets disconnected and you want to catch that so that you can issue a new request A and continue doing the separate requests.

That about right?

**Comment by gadam0** [comment]
Thats mostly right.
Request A is a never-ending, chunked, response. Requests B, C, ... are queued until A is ready.
There is a time period of request A where we get the GOAWAY (A1) and the server disconnects the connection (A2). That time period is about 1 minute.
If other requests (B, C, ...) are sent during that period there is a chance that a response on A may be lost because it would be sent after A2.

I would like to know when the GOAWAY occurs at A1 so that I can:
* Prevent other requests B, C, ... from being added to the current multi-handle
* Remove the current request A from the multi-handle
* Cleanup the old multi-handle and create a new multi-handle
* Create the new request A and then start handling the other requests B, C, ...

Is this a good solution to prevent losing messages on request A?

**Comment by bagder** [comment]
A challenge here is that you want low-level information from the connection that libcurl doesn't expose. libcurl won't even spot a GOAWAY sent on a connection if there's no transfer being handled on that connection at the same time. It will only react and see things while transfers are ongoing.

A received GOAWAY on a connection might not take effect until the time for the next transfer when it'll then detect it and make sure to create a new connection to use instead of the old one.

I of course would argue that this is a crazy way to do anything over HTTP but it won't help anyone. I'm not sure you can make libcurl work properly with this setup. I would imagine we'd need a new API somehow to better detect the GOAWAY while nothing is being transferred.

**Comment by gadam0** [comment]
I think that I should provide more context. The application that I am working on is a re-implementation of another project that used [netty](https://netty.io/) to manage the HTTP2 connection and that provides a way to register for callbacks for the GOAWAY frame.
That is why I have been focused a solution that uses a callback for the GOAWAY frame. I can understand if that approach will not work in libcurl because it is designed to be protocol agnostic.
I think that if I could use `curl_easy_getinfo` to determine the state of the connection associated with the easy handle of the long lived GET request that would also work.

This is the general network loop that exists in my application that uses libcurl.

* Call `curl_multi_perform`, check if `result == CURLM_CALL_MULTI_PERFORM` or `result != CURLM_OK`
* Check if any of the streams are done using `curl_multi_info_read`
* Clean-up and remove finished streams.
* Read from a queue and if necessary create new requests and add them to the multi-handle.
* Call `curl_multi_wait`
* Loop back to `curl_multi_perform`

If I could use `curl_easy_getinfo` to get some information about the state of the connection associated with the easy handle of the long lived GET request then I could check after cleaning-up finished streams but before adding a new request to the multi-handle.

Could the `connectdata` struct in `Curl_easy` be used to determine the state of the connection in a protocol agnostic way?

I think that it may be necessary to look into `connectdata.proto.httpc` in order to reach `nghttp2_session*` inside of `http_conn` and then call [`should_close_session`](https://github.com/curl/curl/blob/master/lib/http2.c#L1326-L1330) in-order to determine if the connection would be closed but this only handles the HTTP protocol.

The `ConnectBits` struct within `connectdata` could also be used to check if the [`close`](https://github.com/curl/curl/blob/master/lib/urldata.h#L423) bit was set but I am not sure how this information could be safely exposed.
I see [this section in the libcurl internals doc](https://ec.haxx.se/internals#everything-is-state-machines) that says "Everything is state machines". Is there anything about the connection that could be exposed as an enum that a user of `curl_easy_getinfo` could use?

**Comment by bagder** [comment]
I don't consider this a curl bug or issue and don't see any immediate action for us here. I'm therefor closing this entry.

From my perspective, you have an application that leans and relies (too) heavily on the underlying connection behavior, which makes it require low-level control of the transfers, to an extent that libcurl  doesn't offer.

I'm open for discussions on how to improve libcurl to better support your use case, but then I think it should be driven either as a discussion/brain-storm session on the curl-library mailing list or perhaps even better as a draft PR with some basic code showing how it would work.
